server:
  port: 9090
spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    user:
      password: password

jwt:
  secret: ercanemirleroglu
